### PR TITLE
ping: Save last link configuration for manual input

### LINKED ISSUE #311: Last link configuration is not working for udp
1. Connects with UDP.
2. Open the interface again.
3. Will not connect.

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #311

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

File: src/sensor/ping.cpp [hunk 1]
```diff
@@ -167,6 +167,7 @@ void Ping::addDetectionLink(LinkType connType, const QStringList& connString)
 void Ping::connectLink(LinkType connType, const QStringList& connString)
 {
     Sensor::connectLink(LinkConfiguration{connType, connString});
+    SettingsManager::self()->lastLinkConfiguration(*link()->configuration());
```
Comment (jaxxzer) [inline src/sensor/ping.cpp]: I believe we should connect connectLink to connectionDetected, and move the first requests here.

Comment (patrickelectric) [reply src/sensor/ping.cpp]: This is already done. This function is called by the QML part, because sensor does not provide it as Q_INVOKABLE. This is a result of a bug where QML can't handle functions with default values or with the same name.

**Comment by jaxxzer** [comment]
I am concerned about the direction of this 'connect sensor' process and the structure around it.

I feel like the connection and logic should be **simply** `ProtocolDetector::connectionDetected -> Ping::connectLink`.

In this patch we have `ProtocolDetector::connectionDetected -> **Sensor**::connectLink` and also `ProtocolDetector::connectionDetected -> Ping::startPreconfigurationProcess`

We have a third overload of `connectLink` in Ping that does not match/exist in the parent Sensor class.

I have two questions:
- Is there any guarantee of the order that the connects run (in Sensor and Ping, both are connecting independently) after ProtocolDetector::connectionDetected is signaled?
- Do you think we can unify the handling of this between sensor and Ping? Can we make Ping override connectLink, so that Ping's method is called in the `ProtocolDetector::connectionDetected -> **Sensor**::connectLink` [connection](https://github.com/bluerobotics/ping-viewer/blob/8ef71de26cc8d83dd88c9573212c565fd037e5df/src/sensor/sensor.cpp#L34)?

File: src/sensor/ping.cpp [hunk 2]
```diff
@@ -120,6 +102,34 @@ Ping::Ping() : Sensor()
     detectorThread()->start();
 }
 
+void Ping::startPreConfigurationProcess()
+{
+    qCDebug(PING_PROTOCOL_PING) << "Start pre configuration task and requests.";
+    if(!link()->isWritable()) {
+        qCDebug(PING_PROTOCOL_PING) << "It's not possible to set last configuration when link is writable.";
```
[the remark this answers is not in the document]
Comment (patrickelectric) [reply src/sensor/ping.cpp]: @jaxxzer 	done.

**Comment by patrickelectric** [comment]
> I feel like the connection and logic should be simply ProtocolDetector::connectionDetected -> Ping::connectLink.

This is done by the sensor part, because all sensors will need connections and protocol detections AFAIK. Moving this to ping will make all sensors definition to have the same code, that could be in sensor base class.

> In this patch we have two slots that are called ProtocolDetector::connectionDetected -> **Sensor**::connectLink and also ProtocolDetector::connectionDetected -> Ping::startPreconfigurationProcess

This was done based on the code that existed. Moving it to use sensor now.

> We have a third overload of connectLink in Ping that does not match/exist in the parent Sensor class, and is also surprisingly not involved during the autodetect/connection process.

This was because of some problems with QML and c++ structures, I can do some work to fix that.

File: src/sensor/ping.cpp [hunk 3]
```diff
@@ -120,6 +99,34 @@ Ping::Ping() : Sensor()
...
+    request(Ping1DNamespace::Speed_of_sound);
+
+    // Start periodic request timer
+    _periodicRequestTimer.start();
+
+    // Save configuration
+    SettingsManager::self()->lastLinkConfiguration(*link()->configuration());
+
+    // Start configuration
+    setLastPingConfiguration();
```
Comment (jaxxzer) [inline src/sensor/ping.cpp]: Are we guaranteeded that we will have the correct srcId for the device at this point so that we load the correct settings?

**Comment by patrickelectric** [comment]
@jaxxzer thank you for making the PR awesome and figuring out so much things !
