### PR TITLE
Fix singleton self call

### LINKED ISSUE #819: Remove memory leak from singletons self calls

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #819

### CODE REVIEW

File: src/devicemanager/devicemanager.cpp [hunk 1]
```diff
@@ -9,6 +11,8 @@ PING_LOGGING_CATEGORY(DEVICEMANAGER, "ping.devicemanager");
 DeviceManager::DeviceManager()
     : _detector(new ProtocolDetector())
 {
+    QQmlEngine::setObjectOwnership(this, QQmlEngine::CppOwnership);
```
Comment (jaxxzer) [inline src/devicemanager/devicemanager.cpp]: can we get a comment? maybe it is common qt programming practice, but I don't know the reason for this addition.

Comment (patrickelectric) [reply src/devicemanager/devicemanager.cpp]: The idea here is to set the ownership of this class as cpp and not javascript, as documented here: https://doc.qt.io/qt-5/qqmlengine.html#ObjectOwnership-enum
The documentation is pretty explicit about what is going on here, we don't want this classes to be deleted by our QML engine but for the cpp scope.

Comment (jaxxzer) [reply src/devicemanager/devicemanager.cpp]: Thank you :+1: I did look on the qt doc, but did not find that enum on my own.
