### PR TITLE
Organize processlog and fix multiple playbacks calls

### LINKED ISSUE #716: It's not possible to play log after running it the first time
based in: https://github.com/bluerobotics/ping-viewer/pull/713#pullrequestreview-279224082

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #716

### CODE REVIEW

File: src/link/processlog.cpp [hunk 1]
```diff
@@ -15,48 +15,46 @@ ProcessLog::ProcessLog(QObject *parent)
...
+    int diffMSecs = 0;
+    int lastMSecs = 0;
 
-    // Check for pause condition and valid log index
-    if(!_play) {
-        QThread::msleep(200);
-        run();
-        return;
-    }
+    while(!_stop) {
```
Comment (tcanabrava) [inline src/link/processlog.cpp]: why are you blocking the thread?

File: src/link/processlog.cpp [hunk 2]
```diff
@@ -15,48 +15,46 @@ ProcessLog::ProcessLog(QObject *parent)
...
+            qCWarning(PING_PROCESSLOG) << "Sample time is negative from previous sample! Trying to recover..";
+            qCDebug(PING_PROCESSLOG) << "First time:" << _log.constFirst().time;
+            qCDebug(PING_PROCESSLOG) << "Last time:" << _log.constLast().time;
+            qCDebug(PING_PROCESSLOG) << "Actual index:" << _logIndex
+                                     << "Time[n-1, n]:" << _log[_logIndex - 1].time << _log[_logIndex].time;
+            continue;
+        }
 
-    QThread::msleep(diffMSecs);
-    run();
```
Comment (jaxxzer) [inline src/link/processlog.cpp]: lol wow
