### PR TITLE
Fix protocol detector scan call

### LINKED ISSUE #457: Calling ProtocolDetector::scan directly freezes the interface

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #457

### CODE REVIEW

File: src/sensor/protocoldetector.cpp [hunk 1]
```diff
@@ -26,9 +26,11 @@ ProtocolDetector::ProtocolDetector()
         {LinkType::Udp, {"192.168.2.2", "9090"}, "BlueRov2 standard connection"},
         {LinkType::Udp, {"127.0.0.1", "1234"}, "Development port"}
     });
+
```
Comment (jaxxzer) [inline src/sensor/protocoldetector.cpp]:
```suggestion

//doing this because it will freeze the main thread if called directly
```
